[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
is-system=true
--via-ir=true
--system-mode=true 
#(add this in the command line after --zksync)

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
